# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile.base                                      :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: fmaurer <fmaurer42@posteo.de>              +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2024/12/01 11:45:58 by fmaurer           #+#    #+#              #
#    Updated: 2026/01/13 13:42:48 by fmaurer          ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME 		= webserv_tests

# The directories..
#
# the magic vpath... by using this we will not have to specify in which
# sub-directory a source file is located. the '%.o' and '%.cpp' wildcards will
# find any file in any directory listed in the VPATH. The same holds true for
# the header files. This also applies to change-detection!
# TL;DR: it makes things pretty easy ;)
VPATH		= ./ ./cpp_tests/
VPATH		+= ../src/ ../inc/

OBJDIR			= obj
WSRV_OBJDIR	= ../obj

INC 			= ../inc

# The files..
WSRV_SRCS_HERE
WSRV_HDRS_HERE

TEST_SRCS			= test-main.cpp \
								test-utils.cpp

TEST_HDRS			= test-utils.hpp

OBJS				= $(patsubst %.cpp,$(OBJDIR)/%.o,$(TEST_SRCS))
WSRV_OBJS		= $(patsubst %.cpp,$(WSRV_OBJDIR)/%.o,$(WSRV_SRCS))

# The programs..
CPP			= c++

# compiler flags
CFLAGS	= -Wall -Werror -Wextra -std=c++98
CFLAGS	+= -g
IFLAGS	= -I $(INC)

all: $(NAME)

$(OBJDIR):
	mkdir -p $(OBJDIR)

$(WSRV_OBJDIR):
	mkdir -p $(WSRV_OBJDIR)

# will never try to compile HDR or any other prequesite specified after `%.cpp`.
# this is because the `%.o` and matched against all .c-files in the current dir.
# !! Attention: Any misspelled filename in HDRS or SRCS will lead to `make` not
# functioning without any meaningful error msg !!
$(OBJDIR)/%.o: %.cpp $(HDRS) | $(OBJDIR)
	$(CPP) $(IFLAGS) $(CFLAGS) -c $< -o $@

$(WSRV_OBJDIR)/%.o: %.cpp $(HDRS) | $(WSRV_OBJDIR)
	$(CPP) $(IFLAGS) $(CFLAGS) -c $< -o $@

$(NAME): $(OBJS) $(WSRV_OBJS)
	$(CPP) $(IFLAGS) $(CFLAGS) -o $@ $^

clean:
	rm -rf $(OBJDIR)

bear: fclean
	bear -- make

run: $(NAME)
	./$(NAME)

fclean: clean
	rm -f $(NAME)

re: fclean $(NAME)

.PHONY: all clean fclean re bear run
