pid ./nginx.pid;
daemon off;
error_log /dev/stdout info;
events {
  worker_connections 1024;
}

http {
  client_body_temp_path ./tmp;
  proxy_temp_path ./tmp;
  fastcgi_temp_path ./tmp;
  uwsgi_temp_path ./tmp;
  scgi_temp_path ./tmp;

  access_log ./access.log;
  server {
    server_name localhost;
    listen localhost:2222;
    root ./www;
    index index.html;
    autoindex on;
    location / {
    }
    location /cgi {
      # fastcgi_pass  localhost:9000;
      fastcgi_index index.sh;

      fastcgi_param SCRIPT_FILENAME ./www/cgi$fastcgi_script_name;
      fastcgi_param QUERY_STRING    $query_string;
      fastcgi_param REQUEST_METHOD  $request_method;
      fastcgi_param CONTENT_TYPE    $content_type;
      fastcgi_param CONTENT_LENGTH  $content_length;
    }
  }
}
