# simple research config
pid ./nginx.pid;
daemon off;
error_log /dev/stdout info;
events {
  worker_connections 1024;
}

http {
  access_log /dev/stdout;
  server {
    server_name localhost;
    listen 80;
    root ./www;
  }

  server {
  access_log /dev/stdout;
    server_name localhost;
    listen 80;
    root ./www;
  }
}
