pid ./nginx.pid;
daemon off;
error_log /dev/stdout info;

#--------------------------------------------------------#
# starting from here the most minimal nginx cfg possible #
#--------------------------------------------------------#

events {
  worker_connections 1024;
}

http {
  server {
    access_log /dev/stdout debug;
    root ./www;
    location / {
      autoindex on;
      index bla.html;
    }
  }
}
