pid ./nginx.pid;
daemon off;
error_log /dev/stdout info;

#--------------------------------------------------------#
# starting from here the most minimal nginx cfg possible #
#--------------------------------------------------------#


# ... but it doesn't do anything, not even open a socket
 
events {
  # worker_connections 1024;
}

http {
  # access_log /dev/stdout;
  # server {
  #   root ./www;
  # }
}
