pid ./nginx.pid;
daemon off;
error_log /dev/stdout info;
events {
  worker_connections 1024;
}

http {
  access_log /dev/stdout;
  server {
    listen      1234;
    server_name localhost;
    root ./www;
    location / {
      index multipart-form.html;
    }
    location /upload-multipart {
      limit_except GET POST {
        deny all;
      }
      client_max_body_size 100;
    }

  }
}
