pid ./nginx.pid;
daemon off;
error_log /dev/stdout info;
events {
  worker_connections 1024;
}

http {
  access_log ./access.log;
  server {
    server_name miep;
    listen 0.0.0.0:4284;
    root ./www;
    index index.html;
    autoindex on;
    location / {
      try_files $uri $uri/ =300;
    }
  }
  server {
    server_name miep;
    listen 10.0.0.1:4284;
    root ./www;
    index index-moep.html;
    autoindex on;
    location / {
      try_files $uri $uri/ =300;
    }
  }
}
