pid ./nginx.pid;
daemon off;
error_log /dev/stdout info;
events {
  worker_connections 1024;
}

http {
  access_log /dev/stdout;
  server {
    server_name miep;
    listen 0.0.0.0:1234;
    root ./www;
    location /bla {

    }
    location /redir {
      return 301 /redir-target;
    }

    location /redir-target {
      index bla.html;
    }
  }
}
