pid ./nginx.pid;
daemon off;
error_log /dev/stdout info;
events {
  worker_connections 1024;
}

http {
  access_log /dev/stdout;
  server {
    server_name miep;
    listen 0.0.0.0:1234;
    root ./www;
    index index.html;
    autoindex on;
    location / {
      limit_except POST GET {
        allow all;
      }
    location /redir1 {
      return 308 https://mofrimit.de;
      }
    location /redir2 {
      return 302 /does/not/exist;
      }

    location /redir3 {
      return 302 httpsa://;
      return 302 httpsa://;
      }
    }
  }

}
