pid ./nginx.pid;
daemon off;
error_log /dev/stdout info;
events {
  worker_connections 1024;
}

http {
  access_log ./access.log;
  server {
    server_name localhost;
    listen 0.0.0.0:4284;
    index index.html;
    autoindex on;
    location / {
      root ./../../moep;
    }
  }
}
