# simple research config
pid ./nginx.pid;
daemon off;
error_log /dev/stdout info;
events {
  worker_connections 1024;
}

http {
  access_log /dev/stdout;
  server {
    server_name 127.0.0.1;
    listen 2222;
    root ./www;
  }
}
