pid ./nginx.pid;
daemon off;
error_log /dev/stdout info;
events {
  worker_connections 1024;
}

http {
  access_log /dev/stdout;
  server {
    server_name localhost;
    listen localhost:1234;
    root ./www;
    index index.html;
  }
}
