pid ./nginx.pid;
daemon off;
error_log /dev/stdout info;
events {
  worker_connections 1024;
}

http {
  access_log /dev/stdout;
  server {
    server_name localhost;
    listen localhost:1234;
    root ./www;

    location / {
      # index index-moep.html;
      root /root;
    }
    # location /moep/miep {
    #
    #   return 301 /moep;
    #   # # Ahaa!!! nginx takes location-roots always relative to server root!
    #   # root /../../moep;
    #   # index index-moep.html;
    # }
  }
}
