/* ************************************************************************** */
/*                                                                            */
/*                                                        :::      ::::::::   */
/*   Response_HandlePost.cpp                            :+:      :+:    :+:   */
/*                                                    +:+ +:+         +:+     */
/*   By: fmaurer <fmaurer42@posteo.de>              +#+  +:+       +#+        */
/*                                                +#+#+#+#+#+   +#+           */
/*   Created: 2026/05/14 17:51:57 by fmaurer           #+#    #+#             */
/*   Updated: 2026/05/14 22:15:26 by fmaurer          ###   ########.fr       */
/*                                                                            */
/* ************************************************************************** */

#include "Logger.hpp"
#include "Request.hpp"
#include "Response.hpp"
#include "VServer.hpp"
#include "WsrvLib.hpp"
#include "utils.hpp"

#include <fstream>

// this means we have a no-cgi route but received a body to process. this means
//
//  - either we save it under the names presented as query params, or
//  - if no params are provided, autogenerated name
//  - or if no upload dir is provided return 500
//
// in both of the successful cases we have to return `201 Created` with the
// created file path in `Location`
void Response::_handleSimplePost()
{
  str upDir = _matchedRoute->getUpload();

  if (upDir.empty()) {
    _status = HTTP_500;
    Logger::logSrv(_vsrv->getName(),
        "No upload dir configured for route -> POST fail!",
        WARN);
    return;
  }

  // append upDir to routes root!
  upDir = _matchedRoute->getRoot() + upDir;

  Logger::logBug("upDir: " + upDir);

  // if upload dir is not a dir -> 500
  if (!isDir(upDir))
    _status = HTTP_500;

  str contentType = _req->getHeaders()["content-type"];

  // handle
  if (contentType.empty()) {
    _handleSimplePostFile(upDir);
    return;
  }

  // isolate mimeType from stuff like encoding and whatnot
  size_t semicolon = contentType.find(';');
  if (semicolon != str::npos)
    contentType = contentType.substr(semicolon);
  str mimeType = strip(contentType);

  Logger::logBug("Got this mimeType: " + mimeType);

  if (mimeType == "multipart/form-data" ||
      mimeType == "application/x-www-form-urlencoded")
    _handleSimplePostForm(upDir, mimeType);
  else
    _handleSimplePostFile(upDir, mimeType);
}

static str generateFname(constr& dir, constr& ext)
{
  // TODO this would be really easily made configurable via cfg!
  // -> add directive defaultUploadName!
  str           defName("wsrvUpload");
  str           fname;
  std::set<str> files = listDirFiles(dir, false);

  Logger::logBug("files: " + getStrSetAsStr(files));

  if (files.empty())
    return "";

  u32 cnt = 0;
  fname   = defName + u32ToStr(cnt) + ext;
  while (files.find(fname) != files.end()) {
    ++cnt;
    fname = defName + u32ToStr(cnt) + ext;
  }
  return fname;
}

void Response::_handleSimplePostFile(constr& upDir, constr& mimeType)
{
  std::map<str, str>& query = _reqline.target.getQuery();
  str                 ext   = "." + WsrvLib::getExtFromMimeType(mimeType);
  str                 fname;

  // try to set fname from query
  if (!query.empty()) {
    if (query.find("filename") != query.end())
      fname = query["filename"];
    else if (query.find("name") != query.end())
      fname = query["name"];
  }

  // try to autogenerate fname
  if (fname.empty() || !isValidFname(fname))
    fname = generateFname(upDir, ext);

  // generateFname also failed, so there must be something fishy with the upDir
  if (fname.empty()) {
    _status = HTTP_500;
    return;
  }

  if (fname.rfind(ext) == str::npos) {
    fname += ext;
  }

  str fullPath = upDir + "/" + fname;

  std::ofstream outfile(fullPath.c_str());

  if (outfile)
    outfile.write(&_req->getBodyData()[0], _req->getBody().getSize());

  if (!outfile)
    _status = HTTP_500;
  else {
    _status = HTTP_201;

    // FIXME this should only be the path from root
    _respoHeaders["Location"]     = _matchedRoute->getUpload() + "/" + fname;
    _respoHeaders["Content-Type"] = mimeType;
  }
}

// here i will ignore the query as it might interfer with stuff from form
void Response::_handleSimplePostForm(constr& upDir, constr& mimeType)
{
  (void)upDir, (void)mimeType;
}
