/* ************************************************************************** */
/*                                                                            */
/*                                                        :::      ::::::::   */
/*   Response_HandlePost.cpp                            :+:      :+:    :+:   */
/*                                                    +:+ +:+         +:+     */
/*   By: fmaurer <fmaurer42@posteo.de>              +#+  +:+       +#+        */
/*                                                +#+#+#+#+#+   +#+           */
/*   Created: 2026/05/14 17:51:57 by fmaurer           #+#    #+#             */
/*   Updated: 2026/06/03 10:08:33 by fmaurer          ###   ########.fr       */
/*                                                                            */
/* ************************************************************************** */

#include "Logger.hpp"
#include "Request.hpp"
#include "Response.hpp"
#include "VServer.hpp"
#include "WsrvLib.hpp"
#include "utils.hpp"

#include <fstream>

// this means we have a no-cgi route but received a body to process. this means
//
//  - either we save it under the names presented as query params, or
//  - if no params are provided, autogenerated name
//  - or if no upload dir is provided return 500
//
// in both of the successful cases we have to return `201 Created` with the
// created file path in `Location`
void Response::_handleSimplePost()
{
  str upDir = _matchedRoute->getUpload();

  if (upDir.empty()) {
    _status = HTTP_500;
    Logger::logSrv(_vsrv->getName(),
        "No upload dir configured for route -> POST fail!",
        WARN);
    return;
  }

  // append upDir to routes root!
  upDir = _matchedRoute->getRoot() + upDir;

  // if upload dir is not a dir -> 500
  if (!getFileType(upDir))
    _status = HTTP_500;

  str contentType = _req->getHeaders()["content-type"];

  // handle
  if (contentType.empty()) {
    _handleSimplePostFile(upDir);
    return;
  }

  // isolate mimeType from stuff like encoding and whatnot
  size_t semicolon = contentType.find(';');
  if (semicolon != str::npos)
    contentType = contentType.substr(0, semicolon);
  str mimeType = strip(contentType);

  if (mimeType == "multipart/form-data" ||
      mimeType == "application/x-www-form-urlencoded")
    _handleSimplePostForm(upDir, mimeType);
  else
    _handleSimplePostFile(upDir, mimeType);

  // select response page
  if (_status == HTTP_201)
    _setBodyStatusPage(_respoHeaders["Location"]);
}

static str generateFname(constr& dir, constr& ext)
{
  // TODO this would be really easily made configurable via cfg!
  // -> add directive uploadFilePrefix!
  str           defName("wsrvUpload");
  str           fname;
  std::set<str> files = listDirFiles(dir, false);

  if (files.empty())
    return "";

  u32 cnt = 0;
  fname   = defName + int2str(cnt) + ext;
  while (files.find(fname) != files.end()) {
    ++cnt;
    fname = defName + int2str(cnt) + ext;
  }
  return fname;
}

void Response::_handleSimplePostFile(constr& upDir, constr& mimeType)
{
  Logger::logSrv(
      _vsrv->getName(), "Handling SimplePostFile for mimeType: " + mimeType);

  std::map<str, str>& query = _reqline.target.getQuery();
  str                 fname;

  // try to set fname from query. if there was one provided we will use it as-is
  // modulo invalid fname.
  if (!query.empty()) {
    if (query.find("filename") != query.end())
      fname = query["filename"];
    else if (query.find("name") != query.end())
      fname = query["name"];
  }

  // try to autogenerate fname
  if (fname.empty() || !isValidFname(fname)) {
    str ext = "." + WsrvLib::getExtFromMimeType(mimeType);
    fname   = generateFname(upDir, ext);

    // generateFname also failed, so there must be something fishy with the
    // upDir
    if (fname.empty()) {
      _status = HTTP_500;
      return;
    }

    if (fname.rfind(ext) == str::npos) {
      fname += ext;
    }
  }

  str fullPath = upDir + "/" + fname;

  std::ofstream outfile(fullPath.c_str());

  if (outfile)
    outfile.write(_req->getBodyRawData(), _req->getBodySize());

  if (!outfile) {
    Logger::logDbg0("Response::_handleSimplePostFile", "outfile not good");
    _status = HTTP_500;
  }
  else {
    _status = HTTP_201;

    str up = _matchedRoute->getUpload();
    if (!up.empty() && up[up.length() - 1] != '/')
      up += "/";
    _respoHeaders["Location"] = up + fname;
  }
}

// Well... if only i had more time i would if i could impl this :/
void Response::_handleSimplePostForm(constr& upDir, constr& mimeType)
{
  _handleSimplePostFile(upDir, mimeType);
}
